#!/bin/bash

# Check if user passed an argument
if [ -z "$1" ]; then
  echo "Usage: canto input.mp3"
  exit 1
fi

# Use the argument as the input filename
INPUT_FILE="$1"

# Run whisper with the provided file
whisper "$INPUT_FILE" \
  --task transcribe \
  --output_format srt \
  --output_dir ./ \
  --model medium \
  --fp16 False \
  --language zh \
  --initial_prompt "用粵語嘅方式，乜嘢, 嘅，呢啲，邊度，等。唔好用普通話嘅字 譬如 什么，他，这"


###############################################
###############################################
#### Next step, run convert from _2convert.py


# app path, path to python script to convert 
SCRIPT_DIR=$(dirname "$(readlink -f "$0")")
CONVERT_SCRIPT="$SCRIPT_DIR/_2convert.py"

# music.mp3 to music.srt
BASE_NAME=$(basename "$INPUT_FILE" .mp3)
SRT_NAME="${BASE_NAME}.srt"

# Run the Python conversion script
python3 "$CONVERT_SCRIPT" "$SRT_NAME"
